--
--   PVCS Identifiers :-
--
--       PVCS id          : $Header:   //vm_latest/archives/nm3/install/create_nm3_check_cons.sql-arc   2.2   Jul 04 2013 13:44:58   James.Wadsworth  $
--       Module Name      : $Workfile:   create_nm3_check_cons.sql  $
--       Date into PVCS   : $Date:   Jul 04 2013 13:44:58  $
--       Date fetched Out : $Modtime:   Jul 04 2013 11:56:24  $
--       Version          : $Revision:   2.2  $
--
-----------------------------------------------------------------------------
--    Copyright (c) 2013 Bentley Systems Incorporated. All rights reserved.
-----------------------------------------------------------------------------
--
PROMPT Creating Check Constraint on 'NM_EVENT_ALERT_MAILS'
ALTER TABLE NM_EVENT_ALERT_MAILS
 ADD (CONSTRAINT NEA_SEND_TYPE_CHK CHECK (nea_send_type IN ('TO','CC','BCC')))
/

PROMPT Creating Check Constraint on 'NM_EVENT_ALERT_MAILS'
ALTER TABLE NM_EVENT_ALERT_MAILS
 ADD (CONSTRAINT NEA_SEVERITY_CHK CHECK (nea_severity >= 0))
/

PROMPT Creating Check Constraint on 'NM_EVENT_ALERT_MAILS'
ALTER TABLE NM_EVENT_ALERT_MAILS
 ADD (CONSTRAINT NEA_RECIPIENT_TYPE_CHK CHECK (nea_recipient_type IN ('USER','GROUP')))
/
   
PROMPT Creating Check Constraint on 'NM_INV_NW_ALL'
ALTER TABLE NM_INV_NW_ALL
 ADD (CONSTRAINT NIN_START_DATE_TCHK CHECK (NIN_START_DATE=TRUNC(NIN_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_NW_ALL'
ALTER TABLE NM_INV_NW_ALL
 ADD (CONSTRAINT NIN_END_DATE_TCHK CHECK (NIN_END_DATE=TRUNC(NIN_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_NW_ALL'
ALTER TABLE NM_INV_NW_ALL
 ADD (CONSTRAINT NIN_LOC_MAND_YN_CHK CHECK (nin_loc_mandatory in ('Y','N')))
/
      
PROMPT Creating Check Constraint on 'NM_GROUP_RELATIONS_ALL'
ALTER TABLE NM_GROUP_RELATIONS_ALL
 ADD (CONSTRAINT NGR_START_DATE_TCHK CHECK (NGR_START_DATE=TRUNC(NGR_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_GROUP_RELATIONS_ALL'
ALTER TABLE NM_GROUP_RELATIONS_ALL
 ADD (CONSTRAINT NGR_END_DATE_TCHK CHECK (NGR_END_DATE=TRUNC(NGR_END_DATE)))
/
  
PROMPT Creating Check Constraint on 'NM_FILL_PATTERNS'
ALTER TABLE NM_FILL_PATTERNS
 ADD (CONSTRAINT NFP_ID_CHK CHECK (nfp_id = UPPER(nfp_id)))
/
 
PROMPT Creating Check Constraint on 'NM_GAZ_QUERY_TYPES'
ALTER TABLE NM_GAZ_QUERY_TYPES
 ADD (CONSTRAINT NGQT_ITEM_TYPE_TYPE_CHK CHECK (NGQT_ITEM_TYPE_TYPE IN ('I','E')))
/
       
PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_FG_GREEN_CHK CHECK (nva_fg_green BETWEEN 0 AND 100))
/

PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_FG_BLUE_CHK CHECK (nva_fg_blue BETWEEN 0 AND 100))
/

PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_FG_RED_CHK CHECK (nva_fg_red BETWEEN 0 AND 100))
/

PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_ID_CHK CHECK (nva_id = UPPER(nva_id)))
/

PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_BG_RED_CHK CHECK (nva_bg_red BETWEEN 0 AND 100))
/

PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_BG_GREEN_CHK CHECK (nva_bg_green BETWEEN 0 AND 100))
/

PROMPT Creating Check Constraint on 'NM_VISUAL_ATTRIBUTES'
ALTER TABLE NM_VISUAL_ATTRIBUTES
 ADD (CONSTRAINT NVA_BG_BLUE_CHK CHECK (nva_bg_blue BETWEEN 0 AND 100))
/
 
PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_REV_ALLOW_YN_CHK CHECK (ngt_reverse_allowed IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_MANDATORY CHECK (ngt_mandatory IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_LINEAR_FLAG_YN_CHK CHECK (ngt_linear_flag IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_START_DATE_TCHK CHECK (NGT_START_DATE=TRUNC(NGT_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_SUB_GRP_YN_CHK CHECK (ngt_sub_group_allowed IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_PARTIAL_YN_CHK CHECK (ngt_partial IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_END_DATE_TCHK CHECK (NGT_END_DATE=TRUNC(NGT_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_GROUP_TYPES_ALL'
ALTER TABLE NM_GROUP_TYPES_ALL
 ADD (CONSTRAINT NGT_GROUP_TYPE_UPPER_CHK CHECK (ngt_group_type = UPPER(ngt_group_type)))
/
   
PROMPT Creating Check Constraint on 'NM_GAZ_QUERY'
ALTER TABLE NM_GAZ_QUERY
 ADD (CONSTRAINT NGQ_ITEMS_OR_AREA_CHK CHECK (NGQ_ITEMS_OR_AREA IN ('I','A')))
/

PROMPT Creating Check Constraint on 'NM_GAZ_QUERY'
ALTER TABLE NM_GAZ_QUERY
 ADD (CONSTRAINT NGQ_ENTIRE_REGION_CHK CHECK (DECODE(ngq_query_all_items,'N'
,5,0)+DECODE(ngq_source_id,-1,5,0) != 10))
/

PROMPT Creating Check Constraint on 'NM_GAZ_QUERY'
ALTER TABLE NM_GAZ_QUERY
 ADD (CONSTRAINT NGQ_QUERY_ALL_ITEMS_AREA_CHK CHECK (DECODE(NGQ_ITEMS_OR_AREA,'A',1,0)+DECODE(NGQ_QUERY_ALL_ITEMS,'Y'
,1,0) != 2))
/

PROMPT Creating Check Constraint on 'NM_GAZ_QUERY'
ALTER TABLE NM_GAZ_QUERY
 ADD (CONSTRAINT NGQ_QUERY_ALL_ITEMS_CHK CHECK (NGQ_QUERY_ALL_ITEMS IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_GAZ_QUERY'
ALTER TABLE NM_GAZ_QUERY
 ADD (CONSTRAINT NGQ_OPEN_OR_CLOSED_CHK CHECK (NGQ_OPEN_OR_CLOSED IN ('O','C')))
/
      
PROMPT Creating Check Constraint on 'HIG_HD_LOOKUP_JOIN_DEFS'
ALTER TABLE HIG_HD_LOOKUP_JOIN_DEFS
 ADD (CONSTRAINT HIG_HD_HHL_OUTER_JOIN CHECK (HHL_OUTER_JOIN IN ('Y', 'N')))
/
     
PROMPT Creating Check Constraint on 'NM_MAIL_MESSAGE'
ALTER TABLE NM_MAIL_MESSAGE
 ADD (CONSTRAINT NMM_HTML_CHK CHECK (nmm_html IN ('Y','N')))
/
 
PROMPT Creating Check Constraint on 'NM_GROUP_INV_LINK_ALL'
ALTER TABLE NM_GROUP_INV_LINK_ALL
 ADD (CONSTRAINT NGIL_END_DATE_TCHK CHECK (ngil_end_date=TRUNC(ngil_end_date)))
/

PROMPT Creating Check Constraint on 'NM_GROUP_INV_LINK_ALL'
ALTER TABLE NM_GROUP_INV_LINK_ALL
 ADD (CONSTRAINT NGIL_START_DATE_TCHK CHECK (ngil_start_date=TRUNC(ngil_start_date)))
/
  
PROMPT Creating Check Constraint on 'NM_THEMES_VISIBLE'
ALTER TABLE NM_THEMES_VISIBLE
 ADD (CONSTRAINT NTV_VISIBLE_YN_CHK CHECK (ntv_visible IN ('Y','N')))
/
    
PROMPT Creating Check Constraint on 'NM_THEME_FUNCTIONS_ALL'
ALTER TABLE NM_THEME_FUNCTIONS_ALL
 ADD (CONSTRAINT NTF_SEEN_IN_GIS_CHK CHECK (NTF_SEEN_IN_GIS IN ('N', 'Y')))
/
       
PROMPT Creating Check Constraint on 'NM_NODES_ALL'
ALTER TABLE NM_NODES_ALL
 ADD (CONSTRAINT NO_END_DATE_TCHK CHECK (NO_END_DATE=TRUNC(NO_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_NODES_ALL'
ALTER TABLE NM_NODES_ALL
 ADD (CONSTRAINT NO_START_DATE_TCHK CHECK (NO_START_DATE=TRUNC(NO_START_DATE)))
/
 
PROMPT Creating Check Constraint on 'HIG_STATUS_CODES'
ALTER TABLE HIG_STATUS_CODES
 ADD (CONSTRAINT HSC_START_DATE_TCHK CHECK (HSC_START_DATE=TRUNC(HSC_START_DATE)))
/

PROMPT Creating Check Constraint on 'HIG_STATUS_CODES'
ALTER TABLE HIG_STATUS_CODES
 ADD (CONSTRAINT HSC_END_DATE_TCHK CHECK (HSC_END_DATE=TRUNC(HSC_END_DATE)))
/
 
PROMPT Creating Check Constraint on 'NM_UPLOAD_FILE_GATEWAY_COLS'
ALTER TABLE NM_UPLOAD_FILE_GATEWAY_COLS
 ADD (CONSTRAINT NUFGC_COLUMN_NAME_UPPER_CHK CHECK (nufgc_column_name=UPPER(nufgc_column_name)))
/

PROMPT Creating Check Constraint on 'NM_UPLOAD_FILE_GATEWAY_COLS'
ALTER TABLE NM_UPLOAD_FILE_GATEWAY_COLS
 ADD (CONSTRAINT NUFGC_COLUMN_DATATYPE_CHK CHECK (nufgc_column_datatype IN ('DATE','NUMBER','VARCHAR2')))
/

PROMPT Creating Check Constraint on 'NM_UPLOAD_FILE_GATEWAY_COLS'
ALTER TABLE NM_UPLOAD_FILE_GATEWAY_COLS
 ADD (CONSTRAINT NUFGC_SEQ_CHK CHECK (nufgc_seq = TRUNC(nufgc_seq) AND nufgc_seq BETWEEN 1 AND 5))
/
     
PROMPT Creating Check Constraint on 'HIG_SEQUENCE_ASSOCIATIONS'
ALTER TABLE HIG_SEQUENCE_ASSOCIATIONS
 ADD (CONSTRAINT HSA_UPPERCASE_CHK CHECK (hsa_table_name=UPPER(hsa_table_name) 
AND hsa_column_name=UPPER(hsa_column_name) 
AND hsa_sequence_name=UPPER(hsa_sequence_name)))
/
 
PROMPT Creating Check Constraint on 'NM_ELEMENTS_ALL'
ALTER TABLE NM_ELEMENTS_ALL
 ADD (CONSTRAINT NE_START_DATE_TCHK CHECK (NE_START_DATE=TRUNC(NE_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_ELEMENTS_ALL'
ALTER TABLE NM_ELEMENTS_ALL
 ADD (CONSTRAINT NE_NODE_CHK CHECK ((DECODE(NE_NO_START,Null,0,1)+DECODE(NE_NO_END,Null,0,1) IN (0,2))))
/

PROMPT Creating Check Constraint on 'NM_ELEMENTS_ALL'
ALTER TABLE NM_ELEMENTS_ALL
 ADD (CONSTRAINT NE_UNIQUE_UPPER_CHK CHECK (ne_unique = UPPER(ne_unique)))
/

PROMPT Creating Check Constraint on 'NM_ELEMENTS_ALL'
ALTER TABLE NM_ELEMENTS_ALL
 ADD (CONSTRAINT NE_END_DATE_TCHK CHECK (NE_END_DATE=TRUNC(NE_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_ELEMENTS_ALL'
ALTER TABLE NM_ELEMENTS_ALL
 ADD (CONSTRAINT NE_LENGTH_CHK CHECK (DECODE(ne_type,'G',DECODE(ne_length,NULL,0,1),'P'
,DECODE(ne_length,NULL,0,1),'D'
,DECODE(ne_length,NULL,1,DECODE(ne_length,ABS(ne_length),0,1)),'S'
,DECODE(ne_length,NULL,1,0,1,DECODE(ne_length,ABS(ne_length),0,1)),1)=
0))
/

PROMPT Creating Check Constraint on 'NM_ELEMENTS_ALL'
ALTER TABLE NM_ELEMENTS_ALL
 ADD (CONSTRAINT NE_TYPE_NE_GTY_GROUP_TYPE_CHK CHECK (DECODE(ne_type,'G',1,'P'
,1,0) + DECODE(ne_gty_group_type,Null,1,0) = 1))
/
 
PROMPT Creating Check Constraint on 'HIG_STANDARD_FAVOURITES'
ALTER TABLE HIG_STANDARD_FAVOURITES
 ADD (CONSTRAINT HSTF_CONNECT_LOOP_CHK CHECK (hstf_parent != hstf_child))
/
   
PROMPT Creating Check Constraint on 'NM_TYPE_SUBCLASS'
ALTER TABLE NM_TYPE_SUBCLASS
 ADD (CONSTRAINT NSC_SUB_CLASS_UPPER_CHK CHECK (nsc_sub_class = UPPER(nsc_sub_class)))
/
 
PROMPT Creating Check Constraint on 'NM_THEME_ROLES'
ALTER TABLE NM_THEME_ROLES
 ADD (CONSTRAINT NTHR_MODE_CHK CHECK (nthr_mode in ('NORMAL','READONLY')))
/
  
PROMPT Creating Check Constraint on 'NM_MEMBER_HISTORY'
ALTER TABLE NM_MEMBER_HISTORY
 ADD (CONSTRAINT NMH_NM_END_DATE_TCHK CHECK (NMH_NM_END_DATE=TRUNC(NMH_NM_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_MEMBER_HISTORY'
ALTER TABLE NM_MEMBER_HISTORY
 ADD (CONSTRAINT NMH_NM_START_DATE_TCHK CHECK (NMH_NM_START_DATE=TRUNC(NMH_NM_START_DATE)))
/
    
PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DISP_DP_CHK CHECK (nmc_disp_dp IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DISP_DP_CHK2 CHECK (DECODE(nmc_disp_dp,Null,1,0)+DECODE(nmc_dec_places,Null,1,0) IN (0,2)))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DISPLAY_SIGN_CHK2 CHECK (DECODE(nmc_data_type,'NUMBER',0,1)+DECODE(nmc_display_sign,'Y'
,1,0) < 2))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DISPLAY_SIGN_CHK CHECK (nmc_display_sign IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DISP_DP_CHK3 CHECK (DECODE(nmc_disp_dp,'Y',1,0)+DECODE(nmc_dec_places,0,1,0) != 2))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_SEC_OR_VAL_CHK CHECK (nmc_sec_or_val IN ('VAL','SEC','ALL')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DEC_PLACES_CHK CHECK (DECODE(nmc_dec_places,Null,0,1) + DECODE(nmc_data_type,'NUMBER'
,0,1) = 1))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DATA_TYPE_CHK CHECK (nmc_data_type IN ('DATE','NUMBER','VARCHAR2')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DEC_PLACES_CHK2 CHECK (nmc_dec_places <= nmc_length))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DEC_PLACES_CHK3 CHECK (nmc_dec_places >= 0))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_LENGTH_CHK CHECK (nmc_length > 0 AND nmc_length=TRUNC(nmc_length)))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_ORDER_BY_CHK2 CHECK (DECODE(nmc_order_by,Null,0,1)+DECODE(nmc_order_by_ord,Null,0,1) 
IN (0,2)))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_DEC_PLACES_CHK4 CHECK (nmc_dec_places = TRUNC(nmc_dec_places)))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_PAD_CHK CHECK (nmc_pad IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_ORDER_BY_CHK CHECK (nmc_order_by_ord IN ('ASC','DESC')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_SEQ_NO_CHK CHECK (nmc_seq_no > 0 AND nmc_seq_no=TRUNC(nmc_seq_no)))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_COLS'
ALTER TABLE NM_MRG_OUTPUT_COLS
 ADD (CONSTRAINT NMC_TOTAL_LENGTH_CHK CHECK (nmc_length+nmc_seq_no <= 4000))
/
       
PROMPT Creating Check Constraint on 'NM_INV_DOMAINS_ALL'
ALTER TABLE NM_INV_DOMAINS_ALL
 ADD (CONSTRAINT ID_START_DATE_TCHK CHECK (ID_START_DATE=TRUNC(ID_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_DOMAINS_ALL'
ALTER TABLE NM_INV_DOMAINS_ALL
 ADD (CONSTRAINT ID_DATATYPE_CHK CHECK (id_datatype IN ('VARCHAR2','NUMBER','DATE')))
/

PROMPT Creating Check Constraint on 'NM_INV_DOMAINS_ALL'
ALTER TABLE NM_INV_DOMAINS_ALL
 ADD (CONSTRAINT ID_END_DATE_TCHK CHECK (ID_END_DATE=TRUNC(ID_END_DATE)))
/
    
PROMPT Creating Check Constraint on 'NM_INV_TYPE_GROUPINGS_ALL'
ALTER TABLE NM_INV_TYPE_GROUPINGS_ALL
 ADD (CONSTRAINT ITG_START_DATE_TCHK CHECK (ITG_START_DATE=TRUNC(ITG_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_GROUPINGS_ALL'
ALTER TABLE NM_INV_TYPE_GROUPINGS_ALL
 ADD (CONSTRAINT ITG_RELATION_CHK CHECK (itg_relation IN ('IN', 'AT', 'NONE', 'RELATIVE', 'DERIVED')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_GROUPINGS_ALL'
ALTER TABLE NM_INV_TYPE_GROUPINGS_ALL
 ADD (CONSTRAINT ITG_END_DATE_TCHK CHECK (ITG_END_DATE=TRUNC(ITG_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_GROUPINGS_ALL'
ALTER TABLE NM_INV_TYPE_GROUPINGS_ALL
 ADD (CONSTRAINT ITG_MANDATORY_YN_CHK CHECK (itg_mandatory in ('Y','N')))
/
  
PROMPT Creating Check Constraint on 'NM_X_LOCATION_RULES'
ALTER TABLE NM_X_LOCATION_RULES
 ADD (CONSTRAINT NXL_XSP_MATCH_YN_CHK CHECK (nxl_xsp_match IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_X_LOCATION_RULES'
ALTER TABLE NM_X_LOCATION_RULES
 ADD (CONSTRAINT NXL_EXISTENCE_YN_CHK CHECK (nxl_existence_flag IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_X_LOCATION_RULES'
ALTER TABLE NM_X_LOCATION_RULES
 ADD (CONSTRAINT NXL_CONDITIONAL_YN_CHK CHECK (nxl_conditional IN ('Y','N')))
/
 
PROMPT Creating Check Constraint on 'NM_EVENT_LOG'
ALTER TABLE NM_EVENT_LOG
 ADD (CONSTRAINT NEL_SEVERITY_CHK CHECK (nel_severity >= 0))
/
  
PROMPT Creating Check Constraint on 'NM_LOAD_DESTINATION_DEFAULTS'
ALTER TABLE NM_LOAD_DESTINATION_DEFAULTS
 ADD (CONSTRAINT NLDD_COLUMN_NAME_CHK CHECK (nldd_column_name = UPPER(nldd_column_name)))
/
     
PROMPT Creating Check Constraint on 'NM_INV_ITEM_GROUPINGS_ALL'
ALTER TABLE NM_INV_ITEM_GROUPINGS_ALL
 ADD (CONSTRAINT IIG_END_DATE_TCHK CHECK (IIG_END_DATE=TRUNC(IIG_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_ITEM_GROUPINGS_ALL'
ALTER TABLE NM_INV_ITEM_GROUPINGS_ALL
 ADD (CONSTRAINT IIG_START_DATE_TCHK CHECK (IIG_START_DATE=TRUNC(IIG_START_DATE)))
/
  
PROMPT Creating Check Constraint on 'NM_MAIL_MESSAGE_RECIPIENTS'
ALTER TABLE NM_MAIL_MESSAGE_RECIPIENTS
 ADD (CONSTRAINT NMMR_SEND_TYPE_CHK CHECK (nmmr_send_type IN ('TO','CC','BCC')))
/

PROMPT Creating Check Constraint on 'NM_MAIL_MESSAGE_RECIPIENTS'
ALTER TABLE NM_MAIL_MESSAGE_RECIPIENTS
 ADD (CONSTRAINT NMMR_RCPT_TYPE_CHK CHECK (nmmr_rcpt_type IN ('USER','GROUP')))
/
    
PROMPT Creating Check Constraint on 'NM_JOB_CONTROL'
ALTER TABLE NM_JOB_CONTROL
 ADD (CONSTRAINT NJC_STATUS_CHK CHECK (njc_status IN ('NOT_STARTED','IN_PROGRESS','COMPLETE','ERROR')))
/

PROMPT Creating Check Constraint on 'NM_JOB_CONTROL'
ALTER TABLE NM_JOB_CONTROL
 ADD (CONSTRAINT NJC_UNIQUE_CHK CHECK (njc_unique = UPPER(njc_unique)))
/

PROMPT Creating Check Constraint on 'NM_JOB_CONTROL'
ALTER TABLE NM_JOB_CONTROL
 ADD (CONSTRAINT NJC_NPE_JOB_ID_CHK CHECK (DECODE(njc_status,'NOT_STARTED'
,0,1)+DECODE(njc_npe_job_id,Null,1,0)!=2))
/
 
PROMPT Creating Check Constraint on 'NM_ERRORS'
ALTER TABLE NM_ERRORS
 ADD (CONSTRAINT NER_ID_CHK CHECK (ner_id=TRUNC(ner_id) AND ner_id > 0))
/
     
PROMPT Creating Check Constraint on 'NM_TYPE_COLUMNS'
ALTER TABLE NM_TYPE_COLUMNS
 ADD (CONSTRAINT NTC_DISPLAYED_YN_CHK CHECK (ntc_displayed IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPE_COLUMNS'
ALTER TABLE NM_TYPE_COLUMNS
 ADD (CONSTRAINT NTC_UNIQUE_FORMAT_CHK CHECK (DECODE(ntc_unique_seq, NULL, 'N', 'V'
) || DECODE(ntc_unique_format, NULL, 'N', 'V') NOT IN ('NV')))
/

PROMPT Creating Check Constraint on 'NM_TYPE_COLUMNS'
ALTER TABLE NM_TYPE_COLUMNS
 ADD (CONSTRAINT NTC_MANDATORY_YN_CHK CHECK (ntc_mandatory IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPE_COLUMNS'
ALTER TABLE NM_TYPE_COLUMNS
 ADD (CONSTRAINT NTC_INHERIT_YN_CHK CHECK (ntc_inherit IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPE_COLUMNS'
ALTER TABLE NM_TYPE_COLUMNS
 ADD (CONSTRAINT NTC_DISPLAYED_MANDATORY_CHK CHECK (DECODE(ntc_displayed,'N',1,0)+DECODE(ntc_mandatory,'Y',1,0)!=2))
/

PROMPT Creating Check Constraint on 'NM_TYPE_COLUMNS'
ALTER TABLE NM_TYPE_COLUMNS
 ADD (CONSTRAINT NTC_DOMAIN_COL_TYPE_CHK CHECK (DECODE(ntc_domain,Null,0,1)+DECODE(ntc_column_type,'VARCHAR2',0,1)!=2))
/
     
PROMPT Creating Check Constraint on 'NM_INV_CATEGORY_MODULES'
ALTER TABLE NM_INV_CATEGORY_MODULES
 ADD (CONSTRAINT ICM_UPDATABLE_CHK CHECK (icm_updatable IN ('Y', 'N')))
/
   
PROMPT Creating Check Constraint on 'HIG_OPTION_LIST'
ALTER TABLE HIG_OPTION_LIST
 ADD (CONSTRAINT HOL_MIXED_CASE_DATATYPE_CHK CHECK (DECODE(hol_mixed_case,'Y',1,0)+DECODE(hol_datatype,'VARCHAR2'
,0,4) != 5))
/

PROMPT Creating Check Constraint on 'HIG_OPTION_LIST'
ALTER TABLE HIG_OPTION_LIST
 ADD (CONSTRAINT HOL_USER_OPTION_CHK CHECK (HOL_USER_OPTION IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'HIG_OPTION_LIST'
ALTER TABLE HIG_OPTION_LIST
 ADD (CONSTRAINT HOL_DATATYPE_CHK CHECK (hol_datatype IN ('DATE','VARCHAR2','NUMBER')))
/

PROMPT Creating Check Constraint on 'HIG_OPTION_LIST'
ALTER TABLE HIG_OPTION_LIST
 ADD (CONSTRAINT HOL_DATATYPE_DOMAIN_CHK CHECK (DECODE(hol_datatype,'VARCHAR2',1,0)+DECODE(hol_domain,Null,0,5)!=5))
/

PROMPT Creating Check Constraint on 'HIG_OPTION_LIST'
ALTER TABLE HIG_OPTION_LIST
 ADD (CONSTRAINT HOL_MIXED_CASE_CHK CHECK (hol_mixed_case IN ('Y','N')))
/
       
PROMPT Creating Check Constraint on 'NM_OPERATION_DATA'
ALTER TABLE NM_OPERATION_DATA
 ADD (CONSTRAINT NOD_SEQ_CHK CHECK (nod_seq=TRUNC(nod_seq)))
/

PROMPT Creating Check Constraint on 'NM_OPERATION_DATA'
ALTER TABLE NM_OPERATION_DATA
 ADD (CONSTRAINT NOD_MANDATORY_CHK CHECK (nod_mandatory IN ('Y', 'N')))
/

PROMPT Creating Check Constraint on 'NM_OPERATION_DATA'
ALTER TABLE NM_OPERATION_DATA
 ADD (CONSTRAINT NOD_DATA_TYPE_CHK CHECK (nod_data_type IN ('DATE','NUMBER','VARCHAR2')))
/
  
PROMPT Creating Check Constraint on 'HIG_HD_COMMON_GATEWAYS'
ALTER TABLE HIG_HD_COMMON_GATEWAYS
 ADD (CONSTRAINT HHG_NAME_UPPER_CHK CHECK (hhg_name = UPPER(hhg_name)))
/
  
PROMPT Creating Check Constraint on 'NM_TYPE_SUBCLASS_RESTRICTIONS'
ALTER TABLE NM_TYPE_SUBCLASS_RESTRICTIONS
 ADD (CONSTRAINT NSR_ALLOWED_YN_CHK CHECK (nsr_allowed IN ('Y','N')))
/
        
PROMPT Creating Check Constraint on 'HIG_DISCO_TABLES'
ALTER TABLE HIG_DISCO_TABLES
 ADD (CONSTRAINT HDT_TABLE_NAME_CHK CHECK (hdt_table_name=UPPER(hdt_table_name)))
/
 
PROMPT Creating Check Constraint on 'NM_TEMP_INV_ITEMS'
ALTER TABLE NM_TEMP_INV_ITEMS
 ADD (CONSTRAINT TII_END_DATE_TCHK CHECK (TII_END_DATE=TRUNC(TII_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_TEMP_INV_ITEMS'
ALTER TABLE NM_TEMP_INV_ITEMS
 ADD (CONSTRAINT TII_START_DATE_TCHK CHECK (TII_START_DATE=TRUNC(TII_START_DATE)))
/
 
PROMPT Creating Check Constraint on 'NM_INV_ITEMS_ALL'
ALTER TABLE NM_INV_ITEMS_ALL
 ADD (CONSTRAINT IIT_START_DATE_TCHK CHECK (IIT_START_DATE=TRUNC(IIT_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_ITEMS_ALL'
ALTER TABLE NM_INV_ITEMS_ALL
 ADD (CONSTRAINT IIT_END_DATE_TCHK CHECK (IIT_END_DATE=TRUNC(IIT_END_DATE)))
/
   
PROMPT Creating Check Constraint on 'NM_JOB_OPERATIONS'
ALTER TABLE NM_JOB_OPERATIONS
 ADD (CONSTRAINT NJO_STATUS_CHK CHECK (njo_status IN ('NOT_STARTED','IN_PROGRESS','COMPLETE','ERROR')))
/

PROMPT Creating Check Constraint on 'NM_JOB_OPERATIONS'
ALTER TABLE NM_JOB_OPERATIONS
 ADD (CONSTRAINT NJO_SEQ_CHK CHECK (njo_seq=TRUNC(njo_seq)))
/

PROMPT Creating Check Constraint on 'NM_JOB_OPERATIONS'
ALTER TABLE NM_JOB_OPERATIONS
 ADD (CONSTRAINT NJO_BEGIN_MP_CHK CHECK (njo_begin_mp >= 0))
/
 
PROMPT Creating Check Constraint on 'NM_MRG_SECTIONS_ALL'
ALTER TABLE NM_MRG_SECTIONS_ALL
 ADD (CONSTRAINT NMS_IN_RESULTS_CHK CHECK (nms_in_results IN ('Y', 'N')))
/
  
PROMPT Creating Check Constraint on 'HIG_HD_SELECTED_COLS'
ALTER TABLE HIG_HD_SELECTED_COLS
 ADD (CONSTRAINT HIG_HD_HHC_DISPLAYED CHECK (HHC_DISPLAYED IN ('Y', 'N')))
/

PROMPT Creating Check Constraint on 'HIG_HD_SELECTED_COLS'
ALTER TABLE HIG_HD_SELECTED_COLS
 ADD (CONSTRAINT HIG_HD_HHC_SUMMARY_VIEW CHECK (HHC_SUMMARY_VIEW IN ('Y', 'N')))
/
    
PROMPT Creating Check Constraint on 'NM_AUDIT_KEY_COLS'
ALTER TABLE NM_AUDIT_KEY_COLS
 ADD (CONSTRAINT NKC_CHECK_SEQ CHECK (nkc_seq_no IN (1,2,3,4,5,6,7,8,9,10)))
/
          
PROMPT Creating Check Constraint on 'NM_LAYER_TREE'
ALTER TABLE NM_LAYER_TREE
 ADD (CONSTRAINT NLTR_PARENT_CHILD_CHK CHECK (nltr_parent != nltr_child))
/

PROMPT Creating Check Constraint on 'NM_LAYER_TREE'
ALTER TABLE NM_LAYER_TREE
 ADD (CONSTRAINT NLTR_TYPE_CHK CHECK (nltr_type IN ('F','M')))
/
  
PROMPT Creating Check Constraint on 'DOC_GATEWAYS'
ALTER TABLE DOC_GATEWAYS
 ADD (CONSTRAINT DGT_START_DATE_TCHK CHECK (DGT_START_DATE=TRUNC(DGT_START_DATE)))
/

PROMPT Creating Check Constraint on 'DOC_GATEWAYS'
ALTER TABLE DOC_GATEWAYS
 ADD (CONSTRAINT DGT_END_DATE_TCHK CHECK (DGT_END_DATE=TRUNC(DGT_END_DATE)))
/
 
PROMPT Creating Check Constraint on 'NM_TYPE_INCLUSION'
ALTER TABLE NM_TYPE_INCLUSION
 ADD (CONSTRAINT NTI_AUTO_CREATE_YN_CHK CHECK (nti_auto_create IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPE_INCLUSION'
ALTER TABLE NM_TYPE_INCLUSION
 ADD (CONSTRAINT NTI_AUTO_INCL_YN_CHK CHECK (nti_auto_include IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPE_INCLUSION'
ALTER TABLE NM_TYPE_INCLUSION
 ADD (CONSTRAINT NTI_REV_ALLOW_YN_CHK CHECK (nti_reverse_allowed IN ('Y','N')))
/
    
PROMPT Creating Check Constraint on 'NM_MEMBERS_ALL'
ALTER TABLE NM_MEMBERS_ALL
 ADD (CONSTRAINT NM_START_DATE_TCHK CHECK (NM_START_DATE=TRUNC(NM_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_MEMBERS_ALL'
ALTER TABLE NM_MEMBERS_ALL
 ADD (CONSTRAINT NM_END_DATE_TCHK CHECK (NM_END_DATE=TRUNC(NM_END_DATE)))
/
     
PROMPT Creating Check Constraint on 'NM_X_NW_RULES'
ALTER TABLE NM_X_NW_RULES
 ADD (CONSTRAINT NXN_EXISTENCE_YN_CHK CHECK (nxn_existence_flag IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_X_NW_RULES'
ALTER TABLE NM_X_NW_RULES
 ADD (CONSTRAINT NXN_CONDITIONAL_YN_CHK CHECK (nxn_conditional IN ('Y','N')))
/
   
PROMPT Creating Check Constraint on 'NM_MRG_NIT_DERIVATION'
ALTER TABLE NM_MRG_NIT_DERIVATION
 ADD (CONSTRAINT NMND_MAINTAIN_HISTORY_CHK CHECK (nmnd_maintain_history IN ('Y','N')))
/
      
PROMPT Creating Check Constraint on 'NM_JOB_TYPES'
ALTER TABLE NM_JOB_TYPES
 ADD (CONSTRAINT NJT_NW_LOCK_CHK CHECK (njt_nw_lock IN ('Y', 'N')))
/
     
PROMPT Creating Check Constraint on 'NM_MRG_QUERY_ALL'
ALTER TABLE NM_MRG_QUERY_ALL
 ADD (CONSTRAINT NMQ_CHK CHECK (NMQ_INNER_OUTER_JOIN IN ('I', 'O')))
/

PROMPT Creating Check Constraint on 'NM_MRG_QUERY_ALL'
ALTER TABLE NM_MRG_QUERY_ALL
 ADD (CONSTRAINT NMQ_TRANS_QRY_YN_CHK CHECK (nmq_transient_query IN ('N','Y')))
/
 
PROMPT Creating Check Constraint on 'FINANCIAL_YEARS'
ALTER TABLE FINANCIAL_YEARS
 ADD (CONSTRAINT FYR_CHK1 CHECK (fyr_start_date<fyr_end_date))
/
  
PROMPT Creating Check Constraint on 'NM_MRG_ITA_DERIVATION'
ALTER TABLE NM_MRG_ITA_DERIVATION
 ADD (CONSTRAINT NMITA_SEQ_NO_CHK CHECK (nmid_seq_no > 0))
/

PROMPT Creating Check Constraint on 'NM_MRG_ITA_DERIVATION'
ALTER TABLE NM_MRG_ITA_DERIVATION
 ADD (CONSTRAINT NMITA_ITA_ATTRIB_NAME_CHK CHECK (nmid_ita_attrib_name = UPPER(nmid_ita_attrib_name)))
/
   
PROMPT Creating Check Constraint on 'NM_NT_GROUPINGS_ALL'
ALTER TABLE NM_NT_GROUPINGS_ALL
 ADD (CONSTRAINT NNG_START_DATE_TCHK CHECK (NNG_START_DATE=TRUNC(NNG_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_NT_GROUPINGS_ALL'
ALTER TABLE NM_NT_GROUPINGS_ALL
 ADD (CONSTRAINT NNG_END_DATE_TCHK CHECK (NNG_END_DATE=TRUNC(NNG_END_DATE)))
/
    
PROMPT Creating Check Constraint on 'NM_NODE_USAGES_ALL'
ALTER TABLE NM_NODE_USAGES_ALL
 ADD (CONSTRAINT NNU_START_DATE_TCHK CHECK (NNU_START_DATE=TRUNC(NNU_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_NODE_USAGES_ALL'
ALTER TABLE NM_NODE_USAGES_ALL
 ADD (CONSTRAINT NNU_NODE_TYPE_CHK CHECK (nnu_node_type IN ('S','E')))
/

PROMPT Creating Check Constraint on 'NM_NODE_USAGES_ALL'
ALTER TABLE NM_NODE_USAGES_ALL
 ADD (CONSTRAINT NNU_END_DATE_TCHK CHECK (NNU_END_DATE=TRUNC(NNU_END_DATE)))
/
    
PROMPT Creating Check Constraint on 'NM_PBI_QUERY_ATTRIBS'
ALTER TABLE NM_PBI_QUERY_ATTRIBS
 ADD (CONSTRAINT NQA_OPERATOR_CHK CHECK (NQA_OPERATOR IN ('AND','OR')))
/

PROMPT Creating Check Constraint on 'NM_PBI_QUERY_ATTRIBS'
ALTER TABLE NM_PBI_QUERY_ATTRIBS
 ADD (CONSTRAINT NQA_BRACKET_CHK CHECK (NQA_PRE_BRACKET 
IN ('(','((','(((','((((','(((((')AND NQA_POST_BRACKET 
IN (')','))',')))','))))',')))))')))
/
 
PROMPT Creating Check Constraint on 'NM_NW_XSP'
ALTER TABLE NM_NW_XSP
 ADD (CONSTRAINT NWX_X_SECT_UPPER_CHK CHECK (nwx_x_sect = UPPER(nwx_x_sect)))
/
 
PROMPT Creating Check Constraint on 'HIG_DISCO_FOREIGN_KEYS'
ALTER TABLE HIG_DISCO_FOREIGN_KEYS
 ADD (CONSTRAINT HDFK_PIGS_EAR_CHK CHECK (hdfk_parent_table != hdfk_child_table))
/

PROMPT Creating Check Constraint on 'HIG_DISCO_FOREIGN_KEYS'
ALTER TABLE HIG_DISCO_FOREIGN_KEYS
 ADD (CONSTRAINT HDFK_OUTER_JOIN_CHK CHECK (hdfk_parent_optional = 'N' OR hdfk_child_optional = 'N'))
/

PROMPT Creating Check Constraint on 'HIG_DISCO_FOREIGN_KEYS'
ALTER TABLE HIG_DISCO_FOREIGN_KEYS
 ADD (CONSTRAINT HDFK_YN_CHK CHECK (hdfk_parent_optional IN ('Y','N') 
AND hdfk_child_optional IN ('Y','N')))
/
  
PROMPT Creating Check Constraint on 'DOC_LOCATIONS'
ALTER TABLE DOC_LOCATIONS
 ADD (CONSTRAINT DLC_END_DATE_TCHK CHECK (DLC_END_DATE=TRUNC(DLC_END_DATE)))
/

PROMPT Creating Check Constraint on 'DOC_LOCATIONS'
ALTER TABLE DOC_LOCATIONS
 ADD (CONSTRAINT DLC_START_DATE_TCHK CHECK (DLC_START_DATE=TRUNC(DLC_START_DATE)))
/
          
PROMPT Creating Check Constraint on 'NM_XSP_REVERSAL'
ALTER TABLE NM_XSP_REVERSAL
 ADD (CONSTRAINT XRV_MANUAL_OVER_YN_CHK CHECK (xrv_manual_override IN ('Y','N')))
/
 
PROMPT Creating Check Constraint on 'DOC_QUERY_COLS'
ALTER TABLE DOC_QUERY_COLS
 ADD (CONSTRAINT DQC_DATATYPE_CHK CHECK (dqc_datatype IN ('NUMBER','DATE','VARCHAR2')))
/
    
PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_EXCL_TYPE_CHK CHECK (DECODE(ita_exclusive,'Y',10,0) + DECODE(ita_format,'NUMBER',0,
'VARCHAR2',DECODE(ita_id_domain,Null,5,0),5) != 15))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_EXCL_YN_CHK CHECK (ita_exclusive IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_EXCL_MAND_CHECK CHECK (DECODE(ita_exclusive,'Y',4,0)+DECODE(ita_mandatory_yn,'Y',1,0) != 4))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_DISPLAYED_YN_CHK CHECK (ita_displayed IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_START_DATE_TCHK CHECK (ITA_START_DATE=TRUNC(ITA_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_END_DATE_TCHK CHECK (ITA_END_DATE=TRUNC(ITA_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_QUERYABLE_YN_CHK CHECK (ita_queryable IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_FORMAT_CHK CHECK (ITA_FORMAT IN ('DATE','VARCHAR2','NUMBER')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_COL_IIT_PK_MAND_CHK CHECK (DECODE(ita_attrib_name,'IIT_PRIMARY_KEY'
,4,0)+DECODE(ita_mandatory_yn,'Y',1,0) IN (0,1,5)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_HIST_YN_CHK CHECK (ita_keep_history_yn IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPE_ATTRIBS_ALL'
ALTER TABLE NM_INV_TYPE_ATTRIBS_ALL
 ADD (CONSTRAINT ITA_COL_UPPER_CHK CHECK (ita_attrib_name = UPPER(ita_attrib_name)))
/
  
PROMPT Creating Check Constraint on 'NM_GAZ_QUERY_ATTRIBS'
ALTER TABLE NM_GAZ_QUERY_ATTRIBS
 ADD (CONSTRAINT NGQA_BRACKET_CHK CHECK (NGQA_PRE_BRACKET IN ('(','((','(((','((((','(((((') 
AND NGQA_POST_BRACKET IN (')','))',')))','))))',')))))')))
/

PROMPT Creating Check Constraint on 'NM_GAZ_QUERY_ATTRIBS'
ALTER TABLE NM_GAZ_QUERY_ATTRIBS
 ADD (CONSTRAINT NGQA_OPERATOR_CHK CHECK (NGQA_OPERATOR IN ('AND','OR')))
/
 
PROMPT Creating Check Constraint on 'DOC_MEDIA'
ALTER TABLE DOC_MEDIA
 ADD (CONSTRAINT DMD_START_DATE_TCHK CHECK (DMD_START_DATE=TRUNC(DMD_START_DATE)))
/

PROMPT Creating Check Constraint on 'DOC_MEDIA'
ALTER TABLE DOC_MEDIA
 ADD (CONSTRAINT DMD_END_DATE_TCHK CHECK (DMD_END_DATE=TRUNC(DMD_END_DATE)))
/
 
PROMPT Creating Check Constraint on 'HIG_CHECK_CONSTRAINT_ASSOCS'
ALTER TABLE HIG_CHECK_CONSTRAINT_ASSOCS
 ADD (CONSTRAINT HCCA_UPPERCASE_CHK CHECK (hcca_constraint_name=UPPER(hcca_constraint_name) 
AND hcca_table_name=UPPER(hcca_table_name)))
/
       
PROMPT Creating Check Constraint on 'NM_LOAD_BATCHES'
ALTER TABLE NM_LOAD_BATCHES
 ADD (CONSTRAINT NLB_BATCH_SOURCE_CHK CHECK (nlb_batch_source IN ('S','C')))
/
  
PROMPT Creating Check Constraint on 'HIG_DISCO_TAB_COLUMNS'
ALTER TABLE HIG_DISCO_TAB_COLUMNS
 ADD (CONSTRAINT HDTC_COLUMN_NAME_CHK CHECK (hdtc_column_name=UPPER(hdtc_column_name)))
/

PROMPT Creating Check Constraint on 'HIG_DISCO_TAB_COLUMNS'
ALTER TABLE HIG_DISCO_TAB_COLUMNS
 ADD (CONSTRAINT HDTC_DATATYPE_CHK CHECK (hdtc_datatype IN ('VARCHAR2','NUMBER','DATE')))
/

PROMPT Creating Check Constraint on 'HIG_DISCO_TAB_COLUMNS'
ALTER TABLE HIG_DISCO_TAB_COLUMNS
 ADD (CONSTRAINT HDTC_WORD_WRAP_CHK CHECK (hdtc_word_wrap IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'HIG_DISCO_TAB_COLUMNS'
ALTER TABLE HIG_DISCO_TAB_COLUMNS
 ADD (CONSTRAINT HDTC_VISIBLE_CHK CHECK (hdtc_visible IN ('Y','N')))
/
     
PROMPT Creating Check Constraint on 'NM_UPLOAD_FILE_GATEWAYS'
ALTER TABLE NM_UPLOAD_FILE_GATEWAYS
 ADD (CONSTRAINT NUFG_TABLE_NAME_UPPER_CHK CHECK (nufg_table_name=UPPER(nufg_table_name)))
/
   
PROMPT Creating Check Constraint on 'HIG_USER_FAVOURITES'
ALTER TABLE HIG_USER_FAVOURITES
 ADD (CONSTRAINT HUF_TYPE_CHK CHECK (huf_type IN ('M','F')))
/

PROMPT Creating Check Constraint on 'HIG_USER_FAVOURITES'
ALTER TABLE HIG_USER_FAVOURITES
 ADD (CONSTRAINT HUF_CONNECT_LOOP_CHK CHECK (huf_parent != huf_child))
/
 
PROMPT Creating Check Constraint on 'HIG_HD_MOD_USES'
ALTER TABLE HIG_HD_MOD_USES
 ADD (CONSTRAINT HIG_HD_HHU_LOAD_DATA_CHK CHECK (HHU_LOAD_DATA IN ('Y', 'N')))
/
 
PROMPT Creating Check Constraint on 'NM_INV_ATTRI_LOOKUP_ALL'
ALTER TABLE NM_INV_ATTRI_LOOKUP_ALL
 ADD (CONSTRAINT IAL_START_DATE_TCHK CHECK (IAL_START_DATE=TRUNC(IAL_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_ATTRI_LOOKUP_ALL'
ALTER TABLE NM_INV_ATTRI_LOOKUP_ALL
 ADD (CONSTRAINT IAL_STOP_QUOTE_CHK CHECK ((NVL(INSTR(IAL_VALUE,CHR(39)),0) = 0)))
/

PROMPT Creating Check Constraint on 'NM_INV_ATTRI_LOOKUP_ALL'
ALTER TABLE NM_INV_ATTRI_LOOKUP_ALL
 ADD (CONSTRAINT IAL_END_DATE_TCHK CHECK (IAL_END_DATE=TRUNC(IAL_END_DATE)))
/
   
PROMPT Creating Check Constraint on 'NM_TYPES'
ALTER TABLE NM_TYPES
 ADD (CONSTRAINT NT_DATUM_NODE_CHK CHECK (DECODE(nt_datum,'Y',1,0) + DECODE(nt_node_type,Null,1,0) != 2))
/

PROMPT Creating Check Constraint on 'NM_TYPES'
ALTER TABLE NM_TYPES
 ADD (CONSTRAINT NT_DATUM_YN_CHK CHECK (nt_datum IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPES'
ALTER TABLE NM_TYPES
 ADD (CONSTRAINT NT_TYPE_UPPER_CHK CHECK (nt_type = UPPER(nt_type)))
/

PROMPT Creating Check Constraint on 'NM_TYPES'
ALTER TABLE NM_TYPES
 ADD (CONSTRAINT NT_POP_UNIQUE_YN_CHK CHECK (nt_pop_unique IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_TYPES'
ALTER TABLE NM_TYPES
 ADD (CONSTRAINT NT_LINEAR_YN_CHK CHECK (nt_linear IN ('Y','N')))
/
    
PROMPT Creating Check Constraint on 'NM_TEMP_INV_MEMBERS'
ALTER TABLE NM_TEMP_INV_MEMBERS
 ADD (CONSTRAINT TIM_START_DATE_TCHK CHECK (TIM_START_DATE=TRUNC(TIM_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_TEMP_INV_MEMBERS'
ALTER TABLE NM_TEMP_INV_MEMBERS
 ADD (CONSTRAINT TIM_END_DATE_TCHK CHECK (TIM_END_DATE=TRUNC(TIM_END_DATE)))
/
   
PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_VARCHAR_SIZE_CHK2 CHECK (nlfc_varchar_size BETWEEN 1 AND 4000))
/

PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_DATATYPE_CHK CHECK (nlfc_datatype IN ('VARCHAR2','DATE','NUMBER')))
/

PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_VARCHAR_SIZE_CHK1 CHECK (DECODE(nlfc_datatype,'VARCHAR2'
,0,5) + DECODE(nlfc_varchar_size,Null,0,5) = 5))
/

PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_MANDATORY_CHK CHECK (nlfc_mandatory IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_SEQ_NO_CHK CHECK (nlfc_seq_no>0))
/

PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_HOLDING_COL_CHK CHECK (nlfc_holding_col=UPPER(nlfc_holding_col)))
/

PROMPT Creating Check Constraint on 'NM_LOAD_FILE_COLS'
ALTER TABLE NM_LOAD_FILE_COLS
 ADD (CONSTRAINT NLFC_DATE_FORMAT_MASK_CHK CHECK (DECODE(nlfc_date_format_mask,Null,0,1)+DECODE(nlfc_datatype,'DATE'
,0,1) != 2))
/
   
PROMPT Creating Check Constraint on 'NM_AUDIT_COLUMNS'
ALTER TABLE NM_AUDIT_COLUMNS
 ADD (CONSTRAINT NAC_COL_ID_INTEGER CHECK (DECODE(nac_column_id,TRUNC(nac_column_id),1,0)=1))
/
 
PROMPT Creating Check Constraint on 'NM_NW_AD_TYPES'
ALTER TABLE NM_NW_AD_TYPES
 ADD (CONSTRAINT NAD_PRIMARY_AD_YN_CHK CHECK (nad_primary_ad IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_NW_AD_TYPES'
ALTER TABLE NM_NW_AD_TYPES
 ADD (CONSTRAINT NAD_SINGLE_ROW_YN_CHK CHECK (nad_single_row IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_NW_AD_TYPES'
ALTER TABLE NM_NW_AD_TYPES
 ADD (CONSTRAINT NAD_MANDATORY_YN_CHK CHECK (nad_mandatory IN ('Y','N')))
/
      
PROMPT Creating Check Constraint on 'NM_TYPE_LAYERS_ALL'
ALTER TABLE NM_TYPE_LAYERS_ALL
 ADD (CONSTRAINT NTL_START_DATE_TCHK CHECK (NTL_START_DATE=TRUNC(NTL_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_TYPE_LAYERS_ALL'
ALTER TABLE NM_TYPE_LAYERS_ALL
 ADD (CONSTRAINT NTL_END_DATE_TCHK CHECK (NTL_END_DATE=TRUNC(NTL_END_DATE)))
/
          
PROMPT Creating Check Constraint on 'NM_ASSETS_ON_ROUTE_STORE_HEAD'
ALTER TABLE NM_ASSETS_ON_ROUTE_STORE_HEAD
 ADD (CONSTRAINT NARSH_ENTIRE_CHK CHECK (narsh_entire IN ('Y', 'N')))
/

PROMPT Creating Check Constraint on 'NM_ASSETS_ON_ROUTE_STORE_HEAD'
ALTER TABLE NM_ASSETS_ON_ROUTE_STORE_HEAD
 ADD (CONSTRAINT NARSH_REF_NEGATIVE_CHK CHECK (narsh_ref_negative IN ('Y', 'N')))
/
 
PROMPT Creating Check Constraint on 'NM_PBI_QUERY_TYPES'
ALTER TABLE NM_PBI_QUERY_TYPES
 ADD (CONSTRAINT NQT_ITEM_TYPE_TYPE_CHK CHECK (NQT_ITEM_TYPE_TYPE IN ('I','E')))
/
 
PROMPT Creating Check Constraint on 'NM_AUDIT_TABLES'
ALTER TABLE NM_AUDIT_TABLES
 ADD (CONSTRAINT NAT_INSERT_CHK CHECK (nat_audit_insert IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_AUDIT_TABLES'
ALTER TABLE NM_AUDIT_TABLES
 ADD (CONSTRAINT NAT_IUD_SPECIFIED_CHK CHECK (DECODE(nat_audit_insert,'Y',1,0)+DECODE(nat_audit_update,'Y'
,1,0)+DECODE(nat_audit_delete,'Y',1,0) > 0))
/

PROMPT Creating Check Constraint on 'NM_AUDIT_TABLES'
ALTER TABLE NM_AUDIT_TABLES
 ADD (CONSTRAINT NAT_UPDATE_CHK CHECK (nat_audit_update IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_AUDIT_TABLES'
ALTER TABLE NM_AUDIT_TABLES
 ADD (CONSTRAINT NAT_DELETE_CHK CHECK (nat_audit_delete IN ('Y','N')))
/
 
PROMPT Creating Check Constraint on 'NM_INV_TYPE_ROLES'
ALTER TABLE NM_INV_TYPE_ROLES
 ADD (CONSTRAINT ITR_MODE_CHK CHECK (itr_mode IN ('READONLY', 'NORMAL')))
/
 
PROMPT Creating Check Constraint on 'HIG_CONTACTS'
ALTER TABLE HIG_CONTACTS
 ADD (CONSTRAINT HCT_END_DATE_TCHK CHECK (HCT_END_DATE=TRUNC(HCT_END_DATE)))
/

PROMPT Creating Check Constraint on 'HIG_CONTACTS'
ALTER TABLE HIG_CONTACTS
 ADD (CONSTRAINT HCT_START_DATE_TCHK CHECK (HCT_START_DATE=TRUNC(HCT_START_DATE)))
/
     
PROMPT Creating Check Constraint on 'HIG_SYSTEM_FAVOURITES'
ALTER TABLE HIG_SYSTEM_FAVOURITES
 ADD (CONSTRAINT HSF_CONNECT_LOOP_CHK CHECK (hsf_parent != hsf_child))
/
            
PROMPT Creating Check Constraint on 'NM_LOAD_FILES'
ALTER TABLE NM_LOAD_FILES
 ADD (CONSTRAINT NLF_UNIQUE_CHK CHECK (nlf_unique=UPPER(nlf_unique)))
/
  
PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_FILE'
ALTER TABLE NM_MRG_OUTPUT_FILE
 ADD (CONSTRAINT NMF_YN_CHK CHECK (nmf_csv 
IN ('N')AND nmf_include_header 
IN ('Y','N')AND nmf_include_footer 
IN ('Y','N')AND nmf_route IN ('Y','N')AND nmf_datum IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_FILE'
ALTER TABLE NM_MRG_OUTPUT_FILE
 ADD (CONSTRAINT NMF_TEMPLATE_FILENAME_CHK CHECK (DECODE(nmf_template,'Y'
,0,5) + DECODE(SIGN(LENGTH(nmf_filename)-50),0,5,-1,5,1) != 1))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_FILE'
ALTER TABLE NM_MRG_OUTPUT_FILE
 ADD (CONSTRAINT NMF_TEMPLATE_YN_CHK CHECK (nmf_template IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_FILE'
ALTER TABLE NM_MRG_OUTPUT_FILE
 ADD (CONSTRAINT NMF_APPEND_MRG_AU_PATH_YN_CHK CHECK (nmf_append_merge_au_to_path IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_MRG_OUTPUT_FILE'
ALTER TABLE NM_MRG_OUTPUT_FILE
 ADD (CONSTRAINT NMF_SEP_CHAR_CHK CHECK (DECODE(nmf_csv,'Y',1,0)+DECODE(nmf_sep_char,Null,0,1) IN (0,2)))
/
   
PROMPT Creating Check Constraint on 'DOC_TYPES'
ALTER TABLE DOC_TYPES
 ADD (CONSTRAINT DTP_END_DATE_TCHK CHECK (DTP_END_DATE=TRUNC(DTP_END_DATE)))
/

PROMPT Creating Check Constraint on 'DOC_TYPES'
ALTER TABLE DOC_TYPES
 ADD (CONSTRAINT DTP_START_DATE_TCHK CHECK (DTP_START_DATE=TRUNC(DTP_START_DATE)))
/
  
PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_TOP_YN_CHK CHECK (nit_top IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_FLEX_ITEM_YN_CHK CHECK (nit_flex_item_flag IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_CAT_PNT_CONT_CHK CHECK (nit_category <> 'G' OR (nit_category = 'G' AND nit_pnt_or_cont = 'C')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_X_SECT_YN_CHK CHECK (nit_x_sect_allow_flag IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_UPDATE_YN_CHK CHECK (nit_update_allowed IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_REPLACEABLE_YN_CHK CHECK (nit_replaceable IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_START_DATE_TCHK CHECK (NIT_START_DATE=TRUNC(NIT_START_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_END_LOC_YN_CHK CHECK (nit_end_loc_only IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_END_DATE_TCHK CHECK (NIT_END_DATE=TRUNC(NIT_END_DATE)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_LINEAR_YN_CHK CHECK (nit_linear IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_PNT_CONTIG_CHK CHECK (DECODE(nit_pnt_or_cont,'P',1,0)+DECODE(nit_contiguous,'Y',1,0)<>2))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_INV_TYPE_UPPER_CHK CHECK (nit_inv_type = UPPER(nit_inv_type)))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_MULTIPLE_YN_CHK CHECK (nit_multiple_allowed IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_USE_XY_YN_CHK CHECK (nit_use_xy IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_EXCLUSIVE_YN_CHK CHECK (nit_exclusive IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_INV_TYPES_ALL'
ALTER TABLE NM_INV_TYPES_ALL
 ADD (CONSTRAINT NIT_CONTIGUOUS_YN_CHK CHECK (nit_contiguous IN ('Y','N')))
/
   
PROMPT Creating Check Constraint on 'HIG_CODES'
ALTER TABLE HIG_CODES
 ADD (CONSTRAINT HCO_START_DATE_TCHK CHECK (HCO_START_DATE=TRUNC(HCO_START_DATE)))
/

PROMPT Creating Check Constraint on 'HIG_CODES'
ALTER TABLE HIG_CODES
 ADD (CONSTRAINT HCO_QUOTE_STOP_CHK CHECK ((NVL(INSTR(HCO_CODE,CHR(39)),0) = 0)))
/

PROMPT Creating Check Constraint on 'HIG_CODES'
ALTER TABLE HIG_CODES
 ADD (CONSTRAINT HCO_END_DATE_TCHK CHECK (HCO_END_DATE=TRUNC(HCO_END_DATE)))
/
  
PROMPT Creating Check Constraint on 'HIG_USER_ROLES'
ALTER TABLE HIG_USER_ROLES
 ADD (CONSTRAINT HUR_START_DATE_TCHK CHECK (HUR_START_DATE=TRUNC(HUR_START_DATE)))
/
    
PROMPT Creating Check Constraint on 'DOC_CLASS'
ALTER TABLE DOC_CLASS
 ADD (CONSTRAINT DCL_START_DATE_TCHK CHECK (DCL_START_DATE=TRUNC(DCL_START_DATE)))
/

PROMPT Creating Check Constraint on 'DOC_CLASS'
ALTER TABLE DOC_CLASS
 ADD (CONSTRAINT DCL_END_DATE_TCHK CHECK (DCL_END_DATE=TRUNC(DCL_END_DATE)))
/
        
PROMPT Creating Check Constraint on 'NM_LOAD_DESTINATIONS'
ALTER TABLE NM_LOAD_DESTINATIONS
 ADD (CONSTRAINT NLD_TABLE_NAME_CHK CHECK (nld_table_name=UPPER(nld_table_name)))
/

PROMPT Creating Check Constraint on 'NM_LOAD_DESTINATIONS'
ALTER TABLE NM_LOAD_DESTINATIONS
 ADD (CONSTRAINT NLD_TABLE_SHORT_NAME_CHK CHECK (nld_table_short_name=UPPER(nld_table_short_name)))
/
          
PROMPT Creating Check Constraint on 'NM_EVENT_TYPES'
ALTER TABLE NM_EVENT_TYPES
 ADD (CONSTRAINT NET_UNIQUE_CHK CHECK (net_unique = UPPER(net_unique)))
/
      
PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_DEPENDENCY_CHK CHECK (nth_dependency IN ('D','I')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_LOCN_UPD_YN_CHK CHECK (nth_location_updatable IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_SNAP_THEME_YN_CHK CHECK (nth_snap_to_theme IN ('N','S','A')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_STORAGE_CHK CHECK (nth_storage IN ('S','D')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_LREF_MAND_YN_CHK CHECK (nth_lref_mandatory IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_THEME_TYPE_CHK CHECK (nth_theme_type IN ('SDO','SDE','LOCL')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_USE_HIST_YN_CHK CHECK (nth_use_history IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'NM_THEMES_ALL'
ALTER TABLE NM_THEMES_ALL
 ADD (CONSTRAINT NTH_UPDATE_ON_EDIT_CHK CHECK (nth_update_on_edit IN ('D','I','N')))
/
