--
--   PVCS Identifiers :-
--
--       PVCS id          : $Header:   //vm_latest/archives/nm3/install/create_temp_ext_and_merge.sql-arc   2.1   Jul 04 2013 13:45:00   James.Wadsworth  $
--       Module Name      : $Workfile:   create_temp_ext_and_merge.sql  $
--       Date into PVCS   : $Date:   Jul 04 2013 13:45:00  $
--       Date fetched Out : $Modtime:   Jul 04 2013 11:56:30  $
--       Version          : $Revision:   2.1  $
--
-----------------------------------------------------------------------------
--    Copyright (c) 2013 Bentley Systems Incorporated. All rights reserved.
-----------------------------------------------------------------------------
--
REM SCCS ID Keyword, do no remove
define sccsid = '@(#)create_temp_ext_and_merge.sql	1.2 03/02/01';

DROP TABLE NM_MRG_INV_ITEMS CASCADE CONSTRAINTS ;

CREATE GLOBAL TEMPORARY TABLE NM_MRG_INV_ITEMS
AS SELECT *
FROM nm_inv_items_all
WHERE 1=2;

ALTER TABLE NM_MRG_INV_ITEMS
ADD (
  NQT_SEQ_NO                 NUMBER        NOT NULL,
  PNT_OR_CONT                VARCHAR2 (1)  NOT NULL ) ;


CREATE UNIQUE INDEX NM_MRG_INV_ITEMS_PK ON
  NM_MRG_INV_ITEMS(IIT_NE_ID)
;

CREATE INDEX NM_MRG_INV_ITEMS_IX ON
  NM_MRG_INV_ITEMS(IIT_INV_TYPE, IIT_X_SECT)
;


DROP TABLE NM_MRG_MEMBERS CASCADE CONSTRAINTS ;

CREATE GLOBAL TEMPORARY TABLE NM_MRG_MEMBERS (
  NM_NE_ID_IN      NUMBER (38)   NOT NULL,
  NM_NE_ID_OF      NUMBER (38)   NOT NULL,
  NM_BEGIN_MP      NUMBER        NOT NULL,
  NM_END_MP        NUMBER,
  NM_SEQ_NO        NUMBER (38),
  INV_TYPE         VARCHAR2(4),
  ELEMENT_LENGTH   NUMBER ,
  route_ne_id      NUMBER
  )
ON COMMIT DELETE ROWS ;

CREATE INDEX NM_MRG_MEMBERS_IX2 ON
  NM_MRG_MEMBERS(NM_NE_ID_OF)
;

CREATE INDEX NM_MRG_MEMBERS_IX ON
  NM_MRG_MEMBERS(NM_NE_ID_IN)
;
CREATE INDEX NM_MRG_MEMBERS_IX3 ON
  NM_MRG_MEMBERS(INV_TYPE)
;

DROP TABLE NM_PBI_MEMBERS CASCADE CONSTRAINTS ;

CREATE GLOBAL TEMPORARY TABLE NM_PBI_MEMBERS (
  NM_NE_ID_IN      NUMBER (38)   NOT NULL,
  NM_NE_ID_OF      NUMBER (38)   NOT NULL,
  NM_BEGIN_MP      NUMBER        NOT NULL,
  NM_END_MP        NUMBER,
  NM_SEQ_NO        NUMBER (38),
  INV_TYPE         VARCHAR2(4),
  route_ne_id      NUMBER
  )
ON COMMIT DELETE ROWS;

CREATE INDEX NM_PBI_MEMBERS_IX2 ON
  NM_PBI_MEMBERS(NM_NE_ID_OF)
;

CREATE INDEX NM_PBI_MEMBERS_IX ON
  NM_PBI_MEMBERS(NM_NE_ID_IN)
;
CREATE INDEX NM_PBI_MEMBERS_IX3 ON
  NM_PBI_MEMBERS(INV_TYPE)
;



DROP TABLE NM_MRG_QUERY_MEMBERS_TEMP2 CASCADE CONSTRAINTS ;

CREATE GLOBAL TEMPORARY TABLE NM_MRG_QUERY_MEMBERS_TEMP2 (
  PL_ID        NUMBER,
  NE_ID_OF     NUMBER,
  BEGIN_MP     NUMBER,
  END_MP       NUMBER,
  MEASURE      NUMBER,
  INV_TYPE     VARCHAR2 (30),
  X_SECT       VARCHAR2 (4),
  PNT_OR_CONT  VARCHAR2 (1)  NOT NULL,
  VALUE_ID     NUMBER )
ON COMMIT DELETE ROWS ;


DROP TABLE NM_MRG_QUERY_RESULTS_TEMP CASCADE CONSTRAINTS ;

CREATE GLOBAL TEMPORARY TABLE NM_MRG_QUERY_RESULTS_TEMP (
  NE_ID        NUMBER        NOT NULL,
  INV_TYPE     VARCHAR2 (30)  NOT NULL,
  X_SECT       VARCHAR2 (4),
  PNT_OR_CONT  VARCHAR2 (1)  NOT NULL,
  ATTRIB1      VARCHAR2 (500),
  ATTRIB2      VARCHAR2 (500),
  ATTRIB3      VARCHAR2 (500),
  ATTRIB4      VARCHAR2 (500),
  ATTRIB5      VARCHAR2 (500),
  ATTRIB6      VARCHAR2 (500),
  ATTRIB7      VARCHAR2 (500),
  ATTRIB8      VARCHAR2 (500),
  ATTRIB9      VARCHAR2 (500),
  ATTRIB10     VARCHAR2 (500),
  ATTRIB11     VARCHAR2 (500),
  ATTRIB12     VARCHAR2 (500),
  ATTRIB13     VARCHAR2 (500),
  ATTRIB14     VARCHAR2 (500),
  ATTRIB15     VARCHAR2 (500),
  ATTRIB16     VARCHAR2 (500),
  ATTRIB17     VARCHAR2 (500),
  ATTRIB18     VARCHAR2 (500),
  ATTRIB19     VARCHAR2 (500),
  ATTRIB20     VARCHAR2 (500),
  ATTRIB21     VARCHAR2 (500),
  ATTRIB22     VARCHAR2 (500),
  ATTRIB23     VARCHAR2 (500),
  ATTRIB24     VARCHAR2 (500),
  ATTRIB25     VARCHAR2 (500) )
ON COMMIT DELETE ROWS ;

DROP TABLE NM_NW_TEMP_EXTENTS CASCADE CONSTRAINTS ;

CREATE GLOBAL TEMPORARY TABLE NM_NW_TEMP_EXTENTS
  (NTE_JOB_ID         NUMBER (38)           NOT NULL
  ,NTE_NE_ID_OF       NUMBER (38)           NOT NULL
  ,NTE_BEGIN_MP       NUMBER      DEFAULT 0 NOT NULL
  ,NTE_END_MP         NUMBER
  ,NTE_CARDINALITY    NUMBER
  ,NTE_SEQ_NO         NUMBER
  ,NTE_ROUTE_NE_ID    NUMBER
  ) ON COMMIT DELETE ROWS;


DROP TABLE nm_temp_nodes CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE nm_temp_nodes(
	ntn_route_id	NUMBER        NOT NULL,
	ntn_node_id	  NUMBER        NOT NULL,
	ntn_int_road	VARCHAR2(100),
	ntn_node_type	VARCHAR2(4)   NOT NULL,
	ntn_poe	      NUMBER,
	ntn_seq	      NUMBER,
	CONSTRAINT nm_temp_nodes_pk PRIMARY KEY (ntn_route_id, ntn_node_id ))
ON COMMIT PRESERVE ROWS;
