--
--   PVCS Identifiers :-
--
--       PVCS id          : $Header:   //vm_latest/archives/nm3/install/nm_4400_fix17_ddl.sql-arc   1.1   Jul 04 2013 13:47:14   James.Wadsworth  $
--       Module Name      : $Workfile:   nm_4400_fix17_ddl.sql  $
--       Date into PVCS   : $Date:   Jul 04 2013 13:47:14  $
--       Date fetched Out : $Modtime:   Jul 04 2013 13:34:10  $
--       Version          : $Revision:   1.1  $
--
-----------------------------------------------------------------------------
--    Copyright (c) 2013 Bentley Systems Incorporated. All rights reserved.
-----------------------------------------------------------------------------
--
@v_nm_admin_units_tree.vw
