--
--   PVCS Identifiers :-
--
--       PVCS id          : $Header:   //vm_latest/archives/nm3/admin/utl/pbi_upg.sql-arc   2.1   Jul 04 2013 10:30:12   James.Wadsworth  $
--       Module Name      : $Workfile:   pbi_upg.sql  $
--       Date into PVCS   : $Date:   Jul 04 2013 10:30:12  $
--       Date fetched Out : $Modtime:   Jul 04 2013 10:26:08  $
--       Version          : $Revision:   2.1  $
--
-----------------------------------------------------------------------------
--    Copyright (c) 2013 Bentley Systems Incorporated. All rights reserved.
-----------------------------------------------------------------------------
--
--
CREATE SEQUENCE npq_id_seq;
--
DROP TABLE NM_PBI_QUERY_MEMBERS CASCADE CONSTRAINTS ;
--
DROP TABLE nm_pbi_query_results;
PROMPT Creating Primary Key on 'NM_PBI_QUERY_RESULTS'
ALTER TABLE NM_PBI_QUERY_RESULTS
 ADD CONSTRAINT NQR_PK PRIMARY KEY
  (NQR_JOB_ID)
/
--
CREATE TABLE NM_PBI_QUERY_RESULTS
 (NQR_NPQ_ID         NUMBER (38)    NOT NULL
 ,NQR_JOB_ID         NUMBER (38)    NOT NULL
 ,NQR_SOURCE_ID      NUMBER         NOT NULL
 ,NQR_SOURCE         VARCHAR2(10)   NOT NULL
 ,NQR_DESCRIPTION    VARCHAR2(4000) NOT NULL
 ,NQR_DATE_CREATED   DATE           NOT NULL
 ,NQR_DATE_MODIFIED  DATE           NOT NULL
 ,NQR_MODIFIED_BY    VARCHAR2 (30)  NOT NULL
 ,NQR_CREATED_BY     VARCHAR2 (30)  NOT NULL
 ,CONSTRAINT NQR_PK
  PRIMARY KEY (NQR_NPQ_ID, NQR_JOB_ID )
 );
--
COMMENT ON TABLE NM_PBI_QUERY_RESULTS IS 'Table to hold details of PBI runs';
--
ALTER TABLE NM_PBI_QUERY_RESULTS ADD  CONSTRAINT NQR_NPQ_FK
 FOREIGN KEY (NQR_NPQ_ID)
  REFERENCES NM_PBI_QUERY (NPQ_ID) ON DELETE CASCADE;
--
DROP TABLE NM_PBI_SECTIONS;
--
CREATE TABLE NM_PBI_SECTIONS
  (NPS_NPQ_ID          NUMBER (38)    NOT NULL
  ,NPS_NQR_JOB_ID      NUMBER (38)    NOT NULL
  ,NPS_SECTION_ID      NUMBER (38)    NOT NULL
  ,NPS_OFFSET_NE_ID    NUMBER (38)    NOT NULL
  ,NPS_BEGIN_OFFSET    NUMBER         NOT NULL
  ,NPS_END_OFFSET      NUMBER         NOT NULL
  ,NPS_NE_ID_FIRST     NUMBER         NOT NULL
  ,NPS_BEGIN_MP_FIRST  NUMBER         NOT NULL
  ,NPS_NE_ID_LAST      NUMBER         NOT NULL
  ,NPS_END_MP_LAST     NUMBER         NOT NULL
  ,NPS_DATE_CREATED    DATE           NOT NULL
  ,NPS_DATE_MODIFIED   DATE           NOT NULL
  ,NPS_MODIFIED_BY     VARCHAR2 (30)  NOT NULL
  ,NPS_CREATED_BY      VARCHAR2 (30)  NOT NULL
  ,CONSTRAINT nps_pk
    PRIMARY KEY (NPS_NPQ_ID,NPS_NQR_JOB_ID,NPS_SECTION_ID)
  );
--
COMMENT ON TABLE NM_PBI_SECTIONS IS 'Table which holds details of each set of members for PBI runs';
--
ALTER TABLE NM_PBI_SECTIONS ADD  CONSTRAINT NQS_NPR_FK
 FOREIGN KEY (NPS_NPQ_ID,NPS_NQR_JOB_ID)
  REFERENCES NM_PBI_QUERY_RESULTS (NQR_NPQ_ID, NQR_JOB_ID) ON DELETE CASCADE;
--
DROP TABLE NM_PBI_SECTION_MEMBERS;
--
CREATE TABLE NM_PBI_SECTION_MEMBERS
  (NPM_NPQ_ID         NUMBER (38)    NOT NULL
  ,NPM_NQR_JOB_ID     NUMBER (38)    NOT NULL
  ,NPM_NPS_SECTION_ID NUMBER (38)    NOT NULL
  ,NPM_NE_ID_OF       NUMBER (38)    NOT NULL
  ,NPM_BEGIN_MP       NUMBER         NOT NULL
  ,NPM_END_MP         NUMBER         NOT NULL
  ,NPM_MEASURE        NUMBER         NOT NULL
  ,NPM_DATE_CREATED   DATE           NOT NULL
  ,NPM_DATE_MODIFIED  DATE           NOT NULL
  ,NPM_MODIFIED_BY    VARCHAR2 (30)  NOT NULL
  ,NPM_CREATED_BY     VARCHAR2 (30)  NOT NULL
  ,CONSTRAINT NPM_PK
     PRIMARY KEY ( NPM_NPQ_ID, NPM_NQR_JOB_ID, NPM_NPS_SECTION_ID, NPM_NE_ID_OF, NPM_BEGIN_MP )
  );
--
COMMENT ON TABLE NM_PBI_SECTION_MEMBERS IS 'Table which holds details of each member for PBI runs';
--
ALTER TABLE NM_PBI_SECTION_MEMBERS ADD  CONSTRAINT NPM_NPS_FK
 FOREIGN KEY (NPM_NPQ_ID, NPM_NQR_JOB_ID, NPM_NPS_SECTION_ID)
  REFERENCES NM_PBI_SECTIONS (NPS_NPQ_ID,NPS_NQR_JOB_ID,NPS_SECTION_ID) ON DELETE CASCADE;
--
